//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrucibleReview
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CrucibleReviewDetails
    {
        public int CrucibleReviewID { get; set; }
        public string CrucibleID { get; set; }
        public string JiraTicketID { get; set; }
        public string CreatedUserName { get; set; }
        public string ProjectKey { get; set; }
        public string ReviewDescription { get; set; }
        public string ReviewersComment { get; set; }
        public string IsDefectRaised { get; set; }
        public string ReviewerName { get; set; }
        public string DevelopersReplie { get; set; }
        public System.DateTime CrucibleCreatedDate { get; set; }
        public System.DateTime CrucibleClosedDate { get; set; }
    }
}
